name: motionbert
channels:
  - defaults
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch=*=*cuda11.8*
  - torchvision=*=*cu118*
  - torchaudio=*=*cu118*
  - coverage
  - easydict
  - flake8
  - imageio-ffmpeg
  - interrogate
  - ipdb
  - isort
  - json_tricks
  - matplotlib
  - munkres
  - ocl-icd-system
  - parameterized
  - pillow
  - pip
  - prettytable
  - py-opencv
  - pytest
  - pytest-runner
  - pytorch-metric-learning                         # For one-shot action recognition
  - requests
  - scipy
  - tensorboard
  - tensorboardx
  - tqdm
  - xdoctest
  - yapf
  - pip:
    - smplx[all]                                      # For mesh recovery
    - chumpy
    - roma
    - openmim
    - torch-tb-profiler
    - chumpy
    - xtcocotools
